# Generated by Django 5.1.7 on 2025-04-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kundelik', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailygrade',
            unique_together=set(),
        ),
    ]
