# Generated by Django 5.1.7 on 2025-04-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kundelik', '0002_alter_dailygrade_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examgrade',
            unique_together=set(),
        ),
    ]
