# Generated by Django 5.1.7 on 2025-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundelik', '0002_alter_schedule_task_class_schedule_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
